application:
  port: 8080
services:
  user-service:
    host: user-service
    rpcPort: 5001
  auth-service:
    host: auth-service
    gRpcPort: 50051
  logger-service:
    host: logger-service
    port: 8080
  product-command-service:
    host: product-command-service
    gRpcPort: 50051
  product-query-service:
    host: product-query-service
    rpcPort: 5001
